### ISSUE TITLE
st\ straight 1024

### ISSUE THREAD

**Issue by TehSimulatorGamer** [mbqwertyaaa/gstp#25]
models/gstp/st/04/1024.mdl

forth and another sleeper wooden thingy is missing some textures on north and south side

https://gyazo.com/6b57f0172c6ff4fce4794f9292a96858
https://gyazo.com/7068de27ffcb7bcd3ee7d92e3ef4cf63

**Comment by mbqwertyaaa** [comment]
Fixed in last st\ commit
