### ISSUE TITLE
New Pack Name?

### ISSUE THREAD

**Issue by GoldHeartTheOne** [mbqwertyaaa/gstp#49]
would it be possible to change the name from gstp to ggrp aka G Gauge Railway Pack.

how much would need to change in your files to do this? could there be a way to automatic?

**Comment by mbqwertyaaa** [comment]
Nah bro, that's 300 files I'd need to export again, after changing the name in one place per model. Also gstp looks better than ggrp. It's a trakpak first, even if it's vee 2.5.

**Comment by GoldHeartTheOne** [comment]
ok, then what about using it just at the workshop name?

**Comment by mbqwertyaaa** [comment]
Nope, sorry mate. I've been calling this gstp for how long now? Probably 4 years

**Comment by GoldHeartTheOne** [comment]
but its not just a track pack anymore so it should have a name that covers both tracks and wheels (& boiges, wagons & coaches).
how about G Guage/Scale Railway Pack? and remember this is just the workshop name so it shouldn't affect anything.

**Comment by mbqwertyaaa** [comment]
I understand your concerns, but no. Mag is calling tp3 what he is, even though it encompasses railroading in its entirety. We don't need to change the name.

**Comment by GoldHeartTheOne** [comment]
so what about mags pack, this isnt about his pack (which is what track and singling? and not wheels, bogies, wagons and coaches)
this is about our joint pack, the main reason i want to change the name is cause people would only see it as a track pack & wont know that it has other stuff like wheels, bogies, wagons and coaches. cause guess what? theres like 3-4 other g gauge/scale track packs, so people wont be looking for a track pack.

**Comment by mbqwertyaaa** [comment]
There is usually other stuff in track packs bro. Please just drop it, I am not changing the name.
